[2025-01-05T05:33:21.149+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-05T05:33:21.165+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing2_vsc.is_api_available scheduled__2025-01-05T05:25:00+00:00 [queued]>
[2025-01-05T05:33:21.174+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing2_vsc.is_api_available scheduled__2025-01-05T05:25:00+00:00 [queued]>
[2025-01-05T05:33:21.175+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-05T05:33:21.193+0000] {taskinstance.py:2889} INFO - Executing <Task(HttpSensor): is_api_available> on 2025-01-05 05:25:00+00:00
[2025-01-05T05:33:21.199+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=663) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-05T05:33:21.200+0000] {standard_task_runner.py:72} INFO - Started process 676 to run task
[2025-01-05T05:33:21.202+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_processing2_vsc', 'is_api_available', 'scheduled__2025-01-05T05:25:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/user_dag.py', '--cfg-path', '/tmp/tmpn7lz5t1d']
[2025-01-05T05:33:21.204+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask is_api_available
[2025-01-05T05:33:21.258+0000] {task_command.py:467} INFO - Running <TaskInstance: user_processing2_vsc.is_api_available scheduled__2025-01-05T05:25:00+00:00 [running]> on host cab0b5f06594
[2025-01-05T05:33:21.361+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing2_vsc' AIRFLOW_CTX_TASK_ID='is_api_available' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T05:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-05T05:25:00+00:00'
[2025-01-05T05:33:21.362+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-05T05:33:21.362+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-05T05:33:21.362+0000] {logging_mixin.py:190} INFO - Current task name:is_api_available state:running start_date:2025-01-05 05:33:21.165728+00:00
[2025-01-05T05:33:21.362+0000] {logging_mixin.py:190} INFO - Dag name:user_processing2_vsc and current dag run status:running
[2025-01-05T05:33:21.363+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-05T05:33:21.363+0000] {baseoperator.py:421} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2025-01-05T05:33:21.363+0000] {http.py:139} INFO - Poking: api/
[2025-01-05T05:33:21.374+0000] {base.py:84} INFO - Retrieving connection 'user_api'
[2025-01-05T05:33:21.632+0000] {base.py:336} INFO - Success criteria met. Exiting.
[2025-01-05T05:33:21.644+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-05T05:33:21.645+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=user_processing2_vsc, task_id=is_api_available, run_id=scheduled__2025-01-05T05:25:00+00:00, execution_date=20250105T052500, start_date=20250105T053321, end_date=20250105T053321
[2025-01-05T05:33:21.655+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-05T05:33:21.655+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-05T05:33:21.655+0000] {logging_mixin.py:190} INFO - Dag name:user_processing2_vsc queued_at:2025-01-05 05:33:18.208396+00:00
[2025-01-05T05:33:21.655+0000] {logging_mixin.py:190} INFO - Task hostname:cab0b5f06594 operator:HttpSensor
[2025-01-05T05:33:21.696+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-05T05:33:21.715+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-05T05:33:21.717+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
