[2025-01-04T23:57:10.275+0000] {processor.py:153} INFO - Started process (PID=49) to work on /opt/airflow/dags/dag.py
[2025-01-04T23:57:10.276+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-04T23:57:10.277+0000] {logging_mixin.py:137} INFO - [2025-01-04T23:57:10.277+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-04T23:57:10.334+0000] {logging_mixin.py:137} INFO - [2025-01-04T23:57:10.334+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from airflow.providers.http.operators.http import HttpOperator
ImportError: cannot import name 'HttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py)
[2025-01-04T23:57:10.335+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-04T23:57:10.350+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.077 seconds
[2025-01-04T23:57:40.528+0000] {processor.py:153} INFO - Started process (PID=174) to work on /opt/airflow/dags/dag.py
[2025-01-04T23:57:40.529+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-04T23:57:40.530+0000] {logging_mixin.py:137} INFO - [2025-01-04T23:57:40.530+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-04T23:57:40.552+0000] {logging_mixin.py:137} INFO - [2025-01-04T23:57:40.551+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from airflow.providers.http.operators.http import HttpOperator
ImportError: cannot import name 'HttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py)
[2025-01-04T23:57:40.552+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-04T23:58:26.858+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.047 seconds
[2025-01-04T23:58:57.373+0000] {processor.py:153} INFO - Started process (PID=457) to work on /opt/airflow/dags/dag.py
[2025-01-04T23:58:57.375+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-04T23:58:57.376+0000] {logging_mixin.py:137} INFO - [2025-01-04T23:58:57.376+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-04T23:58:57.394+0000] {logging_mixin.py:137} INFO - [2025-01-04T23:58:57.394+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from airflow.providers.http.operators.http import HttpOperator
ImportError: cannot import name 'HttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py)
[2025-01-04T23:58:57.394+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-04T23:58:57.415+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.047 seconds
[2025-01-04T23:59:27.736+0000] {processor.py:153} INFO - Started process (PID=582) to work on /opt/airflow/dags/dag.py
[2025-01-04T23:59:27.737+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-04T23:59:27.738+0000] {logging_mixin.py:137} INFO - [2025-01-04T23:59:27.737+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-04T23:59:27.760+0000] {logging_mixin.py:137} INFO - [2025-01-04T23:59:27.760+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from airflow.providers.http.operators.http import HttpOperator
ImportError: cannot import name 'HttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py)
[2025-01-04T23:59:27.761+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-04T23:59:27.780+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.049 seconds
